### PR TITLE
Add lock files to .gitignore

### PR DESCRIPTION
**Pull request by wouterkroes**
For our local development environment these lock files are not needed.

### CODE REVIEW

**Comment by swiv98** [comment]
Although I do agree that the lock file is not something we need to to commit, it _does_ have an effect on further use of the repo. Once you have one, it will lock you in anyway, ignored or not. npm5 behavior, but somehow unwanted.
Haven't looked any further but can we add something that stops npm from creating the lockfile at all?

**Comment by peeke** [comment]
Wouldn't it be better to add the lockfile? Since it generates one anyway if you do npm i, I'd rather have one that works for the version you checked out instead of one you accidentally generated sometime.

**Comment by wolfpilot** [comment]
I don't see why we should add them to `.gitignore` in the first place. The entire idea behind lock files is to ensure that anyone installing dependencies gets the same **working** version as everyone else.

I'd rather ask why would we want to ignore the lock files?

**Comment by swiv98** [comment]
Yes, that's a good way to solve my 'problem' too.
"The bootstrap works with such-and-such versions". Nothing else, no surprises. Lockfile used what it was meant for.
So  let's _not_ add the lockfile to .ignore.

**Comment by wouterkroes** [comment]
Okaj, it is then maybe an idea to add the `package-lock.json` & `yarn.lock` to the bootstrap? Cause right now it is not present.

**Pull request closed without merging**
